version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
    depends_on:
      - redis