spring:
  application.name: mega-test-task
  datasource:
    url: jdbc:h2:mem:tasksdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
    port: 587
    username: sarinzhankazbekov@gmail.com
    password: cuyl aksy bmeo couz
    protocol: smtp
    properties.mail.smtp:
          auth: true
          starttls.enable: true

  cache:
      type: redis
  data:
      redis:
        host: localhost
        port: 6379

service:
  external:
    external-api-service:
      url: https://api.restful-api.dev/objects